<?php

return [
    'id' => 'student_scholarship',
    'name' => __('Student Scholarship'),
    'icon' => '<i class="icon-clipboard"></i>',
    'tab' => "General",
    'fields' => [
        [
            'id'            => 'student_scholarship_table_heading',
            'type'          => 'text',
            'value'         => __('edulia.student_scholarship_information'),
            'class'         => '',
            'label_title'   => __('edulia.student_scholarship_heading'),
            'placeholder'   => __('edulia.student_scholarship_heading'),
        ],
        [
            'id'            => 'photo_title',
            'type'          => 'text',
            'value'         => 'Student Photo',
            'class'         => '',
            'label_title'   => __('edulia.photo_title'),
            'placeholder'   => __('edulia.photo_title'),
        ],
        [
            'id'            => 'name_title',
            'type'          => 'text',
            'value'         => 'Name',
            'class'         => '',
            'label_title'   => __('edulia.name_title'),
            'placeholder'   => __('edulia.name_title'),
        ],
        [
            'id'            => 'session_title',
            'type'          => 'text',
            'value'         => 'Session',
            'class'         => '',
            'label_title'   => __('edulia.session_title'),
            'placeholder'   => __('edulia.session_title'),
        ],
        [
            'id'            => 'scholarship_title',
            'type'          => 'text',
            'value'         => 'Scholarship',
            'class'         => '',
            'label_title'   => __('edulia.scholarship_title'),
            'placeholder'   => __('edulia.scholarship_title'),
        ],
        [
            'id'            => 'info_seprator_id',
            'type'          => 'info',
            'label_title'   => __('edulia.table_column_hide_show'),
            'label_desc'    => '', 
        ],
        [
            'id'            => 'student_scholarship_student_photo',
            'type'          => 'switch',
            'class'         => '',
            'label_title'   => '',
            'label_desc'    => '',
            'field_title'   => __('edulia.photo'), 
            'field_desc'    => '', 
            'value'         => '1',
        ],
        [
            'id'            => 'student_scholarship_student_name',
            'type'          => 'switch',
            'class'         => '',
            'label_title'   => '',
            'label_desc'    => '',
            'field_title'   => __('edulia.name'), 
            'field_desc'    => '', 
            'value'         => '1',
        ],
        [
            'id'            => 'student_scholarship_student_session',
            'type'          => 'switch',
            'class'         => '',
            'label_title'   => '',
            'label_desc'    => '',
            'field_title'   => __('edulia.session'), 
            'field_desc'    => '', 
            'value'         => '1', 
        ],
        [
            'id'            => 'student_scholarship_student',
            'type'          => 'switch',
            'class'         => '',
            'label_title'   => '',
            'label_desc'    => '',
            'field_title'   => __('edulia.scholarship'), 
            'field_desc'    => '', 
            'value'         => '1',
        ]
    ]
];
